Modify org name for family integration stream
hmcts/cnp-jenkins-config pull request #721
Opened 2022-03-22 19:17 UTC by cshiwarale

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

Notes:
*
*
*

2022-03-22 22:13 UTC, timja requested changes

2022-03-22 22:13 UTC, timja commented on team-config.yml
> +fis-ds-web:
the key is the product, you should not have multiple apps under here.

use `fis`

```suggestion
fis:
```

2022-03-22 22:13 UTC, timja commented on team-config.yml
> +fis-bulk-scan-api:
```suggestion
fis
```

2022-03-22 23:34 UTC, cshiwarale commented
@timja I was referring to Adoption teams team-config as below, hence created multiple app

adoption-web:
  team: "Adoption"
  namespace:  "adoption"
  slack:
    contact_channel: "#adoption-tech"
    build_notices_channel: "#adoption-tech"
  tags:
    application: adoption-web
adoption-cos-api:
  team: "Adoption"
  namespace:  "adoption"
  slack:
    contact_channel: "#adoption-tech"
    build_notices_channel: "#adoption-tech"
  tags:
    application: adoption-cos-api
adoption-ccd-definitions:
  team: "Adoption"
  namespace:  "adoption"
  slack:
    contact_channel: "#adoption-tech"
    build_notices_channel: "#adoption-tech"
  tags:
    application: adoption-ccd-definitions

2022-03-23 07:29 UTC, timja commented on team-config.yml
> +fis:
Please remove duplicate

2022-03-23 09:20 UTC, cshiwarale commented on team-config.yml
> +fis:
Removed duplicate

2022-03-23 09:22 UTC, timja approved these changes
You probably want to contact Bruce Rawstorne to confirm your application tag, that's likely not the right one but you can trivially update that after

2022-03-23 09:25 UTC, merged